In [1]:
%load_ext autoreload
%autoreload 2
import sys

# instead of creating a package using setup.py or building from a docker/singularity file,
# import the sister directory of src code to be called on in notebook.
# This keeps the notebook free from code to only hold visualizations and is easier to test
# It also helps keep the state of variables clean such that cells aren't run out of order with a mysterious state
sys.path.append("..")

In [2]:
import pandas as pd
import datetime
from datetime import datetime
import time
import numpy as np
from datetime import timedelta
from datetime import date

In [5]:
df1 = pd.read_parquet(
    "/home/aevans/ai2es/lstm/GFS/fh_003/2018/02/20180201_gfs_fh003.parquet"
)

In [6]:
df1

Empty DataFrame
Columns: [time, latitude, longitude, orog, cape, cin, dswrf, dlwrf, tp, sde, t2m, sh2, d2m, r2, u10, v10, prmsl, tcc, gh, valid_time, atmosphere]
Index: []

[0 rows x 21 columns]

In [25]:
df2 = pd.read_parquet(
    "/home/aevans/ai2es/lstm/GFS/fh_003/2018/01/20180102_gfs_fh003.parquet"
)

In [26]:
df2.reset_index()

Empty DataFrame
Columns: [index, time, latitude, longitude, orog, cape, cin, dswrf, dlwrf, tp, sde, t2m, sh2, d2m, r2, u10, v10, prmsl, tcc, gh, valid_time, atmosphere]
Index: []

[0 rows x 22 columns]

In [27]:
def make_dirs(year, month, day, fh, model):
    if not os.path.exists(f"/home/aevans/ai2es/lstm/{model}/fh_{fh}/"):
        os.makedirs(f"/home/aevans/ai2es/lstm/{model}/fh_{fh}/")
    if not os.path.exists(f"/home/aevans/ai2es/lstm/{model}/fh_{fh}/{year}/"):
        os.makedirs(f"/home/aevans/ai2es/lstm/{model}/fh_{fh}/{year}/")
    if not os.path.exists(f"/home/aevans/ai2es/lstm/{model}/fh_{fh}/{year}/{month}/"):
        os.makedirs(f"/home/aevans/ai2es/lstm/{model}/fh_{fh}/{year}/{month}/")

In [28]:
# consider the start date as 2021-february 1 st
start_date = datetime(2018, 1, 1, 0, 0, 0)

# consider the end date as 2021-march 1 st
end_date = datetime(2018, 2, 28, 23, 59, 59)

# delta time
delta = timedelta(days=1)

model = 'gfs'

In [29]:
savedir = "/home/aevans/ai2es/cleaned/GFS/"
fh = str(3).zfill(3)

In [30]:
    # Loop through the date range
    while start_date <= end_date:
        the_df = pd.DataFrame()
        my_date = start_date
        my_time = my_date + timedelta(hours=int(fh))

        # Loop through 24 hours of the day
        for i in np.arange(0, 24, 6):
            my_time = str(my_time)
            print(my_time)
            init = str(i).zfill(2)
            month = str(my_date.strftime("%m"))
            year = str(my_date.strftime("%Y"))
            day = str(my_date.strftime("%d"))

            # Check if the file exists for the given date and forecast hour
            if not os.path.exists(
                f"{savedir}{year}/{month}/{year}{month}{day}_{model.lower()}.t{init}z_{fh.zfill(3)}.parquet"
            ):
                continue
            else:
                # Read the data from the parquet file
                df = pd.read_parquet(
                    f"{savedir}{year}/{month}/{year}{month}{day}_{model.lower()}.t{init}z_{fh.zfill(3)}.parquet"
                ).reset_index()
                print(df['valid_time'].iloc[0])
                # Filter data for the specific time
                new_df = df[df["valid_time"] == my_time]
                the_df = pd.concat([new_df, the_df])

                # Increment time by 6 hours
                time_obj = datetime.strptime(my_time, "%Y-%m-%d %H:%M:%S")
                if model.upper() == "GFS":
                    my_time = time_obj + timedelta(hours=6)
                if model.upper() == "NAM":
                    my_time = time_obj + timedelta(hours=1)

        start_date += delta

        make_dirs(year, month, day, fh, model)
        # Reverse the order of rows and save the data to a new parquet file
        the_df = the_df.iloc[::-1]
        the_df.to_parquet(
            f"/home/aevans/ai2es/lstm/{model}/fh_{fh}/{year}/{month}/{year}{month}{day}_{model.lower()}_fh{fh}.parquet"
        )

2018-01-01 03:00:00
2018-01-01 03:00:00
2018-01-01 09:00:00
2018-01-01 09:00:00
2018-01-01 15:00:00
2018-01-01 15:00:00
2018-01-01 21:00:00
2018-01-01 21:00:00
2018-01-02 03:00:00
2018-01-02 03:00:00
2018-01-02 09:00:00
2018-01-02 09:00:00
2018-01-02 15:00:00
2018-01-02 15:00:00
2018-01-02 21:00:00
2018-01-02 21:00:00
2018-01-03 03:00:00
2018-01-03 03:00:00
2018-01-03 09:00:00
2018-01-03 09:00:00
2018-01-03 15:00:00
2018-01-03 15:00:00
2018-01-03 21:00:00
2018-01-03 21:00:00
2018-01-04 03:00:00
2018-01-04 03:00:00
2018-01-04 09:00:00
2018-01-04 09:00:00
2018-01-04 15:00:00
2018-01-04 15:00:00
2018-01-04 21:00:00
2018-01-04 21:00:00
2018-01-05 03:00:00
2018-01-05 03:00:00
2018-01-05 09:00:00
2018-01-05 09:00:00
2018-01-05 15:00:00
2018-01-05 15:00:00
2018-01-05 21:00:00
2018-01-05 21:00:00
2018-01-06 03:00:00
2018-01-06 03:00:00
2018-01-06 09:00:00
2018-01-06 09:00:00
2018-01-06 15:00:00
2018-01-06 15:00:00
2018-01-06 21:00:00
2018-01-06 21:00:00
2018-01-07 03:00:00
2018-01-07 03:00:00
2018-01-07 09:00:00
2018-01-07 09:00:00
2018-01-07 15:00:00
2018-01-07 15:00:00
2018-01-07 21:00:00
2018-01-07 21:00:00
2018-01-08 03:00:00
2018-01-08 03:00:00
2018-01-08 09:00:00
2018-01-08 09:00:00
2018-01-08 15:00:00
2018-01-08 15:00:00
2018-01-08 21:00:00
2018-01-08 21:00:00
2018-01-09 03:00:00
2018-01-09 03:00:00
2018-01-09 09:00:00
2018-01-09 09:00:00
2018-01-09 15:00:00
2018-01-09 15:00:00
2018-01-09 21:00:00
2018-01-09 21:00:00
2018-01-10 03:00:00
2018-01-10 03:00:00
2018-01-10 09:00:00
2018-01-10 09:00:00
2018-01-10 15:00:00
2018-01-10 15:00:00
2018-01-10 21:00:00
2018-01-10 21:00:00
2018-01-11 03:00:00
2018-01-11 03:00:00
2018-01-11 09:00:00
2018-01-11 09:00:00
2018-01-11 15:00:00
2018-01-11 15:00:00
2018-01-11 21:00:00
2018-01-11 21:00:00
2018-01-12 03:00:00
2018-01-12 03:00:00
2018-01-12 09:00:00
2018-01-12 09:00:00
2018-01-12 15:00:00
2018-01-12 15:00:00
2018-01-12 21:00:00
2018-01-12 21:00:00
2018-01-13 03:00:00
2018-01-13 03:00:00
2018-01-13 09:00:00
2018-01-13 09:00:00
2018-01-13 15:00:00
2018-01-13 15:00:00
2018-01-13 21:00:00
2018-01-13 21:00:00
2018-01-14 03:00:00
2018-01-14 03:00:00
2018-01-14 09:00:00
2018-01-14 09:00:00
2018-01-14 15:00:00
2018-01-14 15:00:00
2018-01-14 21:00:00
2018-01-14 21:00:00
2018-01-15 03:00:00
2018-01-15 03:00:00
2018-01-15 09:00:00
2018-01-15 09:00:00
2018-01-15 15:00:00
2018-01-15 15:00:00
2018-01-15 21:00:00
2018-01-15 21:00:00
2018-01-16 03:00:00
2018-01-16 03:00:00
2018-01-16 09:00:00
2018-01-16 09:00:00
2018-01-16 15:00:00
2018-01-16 15:00:00
2018-01-16 21:00:00
2018-01-16 21:00:00
2018-01-17 03:00:00
2018-01-17 03:00:00
2018-01-17 09:00:00
2018-01-17 09:00:00
2018-01-17 15:00:00
2018-01-17 15:00:00
2018-01-17 21:00:00
2018-01-17 21:00:00
2018-01-18 03:00:00
2018-01-18 03:00:00
2018-01-18 09:00:00
2018-01-18 09:00:00
2018-01-18 15:00:00
2018-01-18 15:00:00
2018-01-18 21:00:00
2018-01-18 21:00:00
2018-01-19 03:00:00
2018-01-19 03:00:00
2018-01-19 09:00:00
2018-01-19 09:00:00
2018-01-19 15:00:00
2018-01-19 15:00:00
2018-01-19 21:00:00
2018-01-19 21:00:00
2018-01-20 03:00:00
2018-01-20 03:00:00
2018-01-20 09:00:00
2018-01-20 09:00:00
2018-01-20 15:00:00
2018-01-20 15:00:00
2018-01-20 21:00:00
2018-01-20 21:00:00
2018-01-21 03:00:00
2018-01-21 03:00:00
2018-01-21 09:00:00
2018-01-21 09:00:00
2018-01-21 15:00:00
2018-01-21 15:00:00
2018-01-21 21:00:00
2018-01-21 21:00:00
2018-01-22 03:00:00
2018-01-22 03:00:00
2018-01-22 09:00:00
2018-01-22 09:00:00
2018-01-22 15:00:00
2018-01-22 15:00:00
2018-01-22 21:00:00
2018-01-22 21:00:00
2018-01-23 03:00:00
2018-01-23 03:00:00
2018-01-23 09:00:00
2018-01-23 09:00:00
2018-01-23 15:00:00
2018-01-23 15:00:00
2018-01-23 21:00:00
2018-01-23 21:00:00
2018-01-24 03:00:00
2018-01-24 03:00:00
2018-01-24 09:00:00
2018-01-24 09:00:00
2018-01-24 15:00:00
2018-01-24 15:00:00
2018-01-24 21:00:00
2018-01-24 21:00:00
2018-01-25 03:00:00
2018-01-25 03:00:00
2018-01-25 09:00:00
2018-01-25 09:00:00
2018-01-25 15:00:00
2018-01-25 15:00:00
2018-01-25 21:00:00
2018-01-25 21:00:00
2018-01-26 03:00:00
2018-01-26 03:00:00
2018-01-26 09:00:00
2018-01-26 09:00:00
2018-01-26 15:00:00
2018-01-26 15:00:00
2018-01-26 21:00:00
2018-01-26 21:00:00
2018-01-27 03:00:00
2018-01-27 03:00:00
2018-01-27 09:00:00
2018-01-27 09:00:00
2018-01-27 15:00:00
2018-01-27 15:00:00
2018-01-27 21:00:00
2018-01-27 21:00:00
2018-01-28 03:00:00
2018-01-28 03:00:00
2018-01-28 09:00:00
2018-01-28 09:00:00
2018-01-28 15:00:00
2018-01-28 15:00:00
2018-01-28 21:00:00
2018-01-28 21:00:00
2018-01-29 03:00:00
2018-01-29 03:00:00
2018-01-29 09:00:00
2018-01-29 09:00:00
2018-01-29 15:00:00
2018-01-29 15:00:00
2018-01-29 21:00:00
2018-01-29 21:00:00
2018-01-30 03:00:00
2018-01-30 03:00:00
2018-01-30 09:00:00
2018-01-30 09:00:00
2018-01-30 15:00:00
2018-01-30 15:00:00
2018-01-30 21:00:00
2018-01-30 21:00:00
2018-01-31 03:00:00
2018-01-31 03:00:00
2018-01-31 09:00:00
2018-01-31 09:00:00
2018-01-31 15:00:00
2018-01-31 15:00:00
2018-01-31 21:00:00
2018-01-31 21:00:00
2018-02-01 03:00:00
2018-02-01 03:00:00
2018-02-01 09:00:00
2018-02-01 09:00:00
2018-02-01 15:00:00
2018-02-01 15:00:00
2018-02-01 21:00:00
2018-02-01 21:00:00
2018-02-02 03:00:00
2018-02-02 03:00:00
2018-02-02 09:00:00
2018-02-02 09:00:00
2018-02-02 15:00:00
2018-02-02 15:00:00
2018-02-02 21:00:00
2018-02-02 21:00:00
2018-02-03 03:00:00
2018-02-03 03:00:00
2018-02-03 09:00:00
2018-02-03 09:00:00
2018-02-03 15:00:00
2018-02-03 15:00:00
2018-02-03 21:00:00
2018-02-03 21:00:00
2018-02-04 03:00:00
2018-02-04 03:00:00
2018-02-04 09:00:00
2018-02-04 09:00:00
2018-02-04 15:00:00
2018-02-04 15:00:00
2018-02-04 21:00:00
2018-02-04 21:00:00
2018-02-05 03:00:00
2018-02-05 03:00:00
2018-02-05 09:00:00
2018-02-05 09:00:00
2018-02-05 15:00:00
2018-02-05 15:00:00
2018-02-05 21:00:00
2018-02-05 21:00:00
2018-02-06 03:00:00
2018-02-06 03:00:00
2018-02-06 09:00:00
2018-02-06 09:00:00
2018-02-06 15:00:00
2018-02-06 15:00:00
2018-02-06 21:00:00
2018-02-06 21:00:00
2018-02-07 03:00:00
2018-02-07 03:00:00
2018-02-07 09:00:00
2018-02-07 09:00:00
2018-02-07 15:00:00
2018-02-07 15:00:00
2018-02-07 21:00:00
2018-02-07 21:00:00
2018-02-08 03:00:00
2018-02-08 03:00:00
2018-02-08 09:00:00
2018-02-08 09:00:00
2018-02-08 15:00:00
2018-02-08 15:00:00
2018-02-08 21:00:00
2018-02-08 21:00:00
2018-02-09 03:00:00
2018-02-09 03:00:00
2018-02-09 09:00:00
2018-02-09 09:00:00
2018-02-09 15:00:00
2018-02-09 15:00:00
2018-02-09 21:00:00
2018-02-09 21:00:00
2018-02-10 03:00:00
2018-02-10 03:00:00
2018-02-10 09:00:00
2018-02-10 09:00:00
2018-02-10 15:00:00
2018-02-10 15:00:00
2018-02-10 21:00:00
2018-02-10 21:00:00
2018-02-11 03:00:00
2018-02-11 03:00:00
2018-02-11 09:00:00
2018-02-11 09:00:00
2018-02-11 15:00:00
2018-02-11 15:00:00
2018-02-11 21:00:00
2018-02-11 21:00:00
2018-02-12 03:00:00
2018-02-12 03:00:00
2018-02-12 09:00:00
2018-02-12 09:00:00
2018-02-12 15:00:00
2018-02-12 15:00:00
2018-02-12 21:00:00
2018-02-12 21:00:00
2018-02-13 03:00:00
2018-02-13 03:00:00
2018-02-13 09:00:00
2018-02-13 09:00:00
2018-02-13 15:00:00
2018-02-13 15:00:00
2018-02-13 21:00:00
2018-02-13 21:00:00
2018-02-14 03:00:00
2018-02-14 03:00:00
2018-02-14 09:00:00
2018-02-14 09:00:00
2018-02-14 15:00:00
2018-02-14 15:00:00
2018-02-14 21:00:00
2018-02-14 21:00:00
2018-02-15 03:00:00
2018-02-15 03:00:00
2018-02-15 09:00:00
2018-02-15 09:00:00
2018-02-15 15:00:00
2018-02-15 15:00:00
2018-02-15 21:00:00
2018-02-15 21:00:00
2018-02-16 03:00:00
2018-02-16 03:00:00
2018-02-16 09:00:00
2018-02-16 09:00:00
2018-02-16 15:00:00
2018-02-16 15:00:00
2018-02-16 21:00:00
2018-02-16 21:00:00
2018-02-17 03:00:00
2018-02-17 03:00:00
2018-02-17 09:00:00
2018-02-17 09:00:00
2018-02-17 15:00:00
2018-02-17 15:00:00
2018-02-17 21:00:00
2018-02-17 21:00:00
2018-02-18 03:00:00
2018-02-18 03:00:00
2018-02-18 09:00:00
2018-02-18 09:00:00
2018-02-18 15:00:00
2018-02-18 15:00:00
2018-02-18 21:00:00
2018-02-18 21:00:00
2018-02-19 03:00:00
2018-02-19 03:00:00
2018-02-19 09:00:00
2018-02-19 09:00:00
2018-02-19 15:00:00
2018-02-19 15:00:00
2018-02-19 21:00:00
2018-02-19 21:00:00
2018-02-20 03:00:00
2018-02-20 03:00:00
2018-02-20 09:00:00
2018-02-20 09:00:00
2018-02-20 15:00:00
2018-02-20 15:00:00
2018-02-20 21:00:00
2018-02-20 21:00:00
2018-02-21 03:00:00
2018-02-21 03:00:00
2018-02-21 09:00:00
2018-02-21 09:00:00
2018-02-21 15:00:00
2018-02-21 15:00:00
2018-02-21 21:00:00
2018-02-21 21:00:00
2018-02-22 03:00:00
2018-02-22 03:00:00
2018-02-22 09:00:00
2018-02-22 09:00:00
2018-02-22 15:00:00
2018-02-22 15:00:00
2018-02-22 21:00:00
2018-02-22 21:00:00
2018-02-23 03:00:00
2018-02-23 03:00:00
2018-02-23 09:00:00
2018-02-23 09:00:00
2018-02-23 15:00:00
2018-02-23 15:00:00
2018-02-23 21:00:00
2018-02-23 21:00:00
2018-02-24 03:00:00
2018-02-24 03:00:00
2018-02-24 09:00:00
2018-02-24 09:00:00
2018-02-24 15:00:00
2018-02-24 15:00:00
2018-02-24 21:00:00
2018-02-24 21:00:00
2018-02-25 03:00:00
2018-02-25 03:00:00
2018-02-25 09:00:00
2018-02-25 09:00:00
2018-02-25 15:00:00
2018-02-25 15:00:00
2018-02-25 21:00:00
2018-02-25 21:00:00
2018-02-26 03:00:00
2018-02-26 03:00:00
2018-02-26 09:00:00
2018-02-26 09:00:00
2018-02-26 15:00:00
2018-02-26 15:00:00
2018-02-26 21:00:00
2018-02-26 21:00:00
2018-02-27 03:00:00
2018-02-27 03:00:00
2018-02-27 09:00:00
2018-02-27 09:00:00
2018-02-27 15:00:00
2018-02-27 15:00:00
2018-02-27 21:00:00
2018-02-27 21:00:00
2018-02-28 03:00:00
2018-02-28 03:00:00
2018-02-28 09:00:00
2018-02-28 09:00:00
2018-02-28 15:00:00
2018-02-28 15:00:00
2018-02-28 21:00:00
2018-02-28 21:00:00

In [31]:
the_df["valid_time"].unique()

array(['2018-02-28T03:00:00.000000000', '2018-02-28T09:00:00.000000000',
       '2018-02-28T15:00:00.000000000', '2018-02-28T21:00:00.000000000'],
      dtype='datetime64[ns]')

In [32]:
the_df

,time,latitude,longitude,orog,cape,cin,dswrf,dlwrf,tp,sde,...,sh2,d2m,r2,u10,v10,prmsl,tcc,gh,valid_time,atmosphere
778,2018-02-28 00:00:00,38.0,-65.0,-0.028477,6.0,-0.003613,0.0,270.292053,0.0000,0.00,...,0.00475,276.552063,57.417107,1.330325,-6.900979,102445.390625,0.0,5562.325684,2018-02-28 03:00:00,0.0
777,2018-02-28 00:00:00,38.0,-65.5,-0.028477,5.0,-0.003613,0.0,270.292053,0.0000,0.00,...,0.00465,276.352051,56.817108,1.330325,-6.540979,102479.796875,0.0,5569.165527,2018-02-28 03:00:00,0.0
776,2018-02-28 00:00:00,38.0,-66.0,-0.028477,0.0,-0.003613,0.0,268.292053,0.0000,0.00,...,0.00453,275.952057,56.217106,1.320325,-6.260979,102507.796875,0.0,5575.945801,2018-02-28 03:00:00,0.0
775,2018-02-28 00:00:00,38.0,-66.5,-0.028477,0.0,-0.003613,0.0,265.292053,0.0000,0.00,...,0.00437,275.452057,55.517105,1.270325,-5.750979,102529.992188,0.0,5582.325684,2018-02-28 03:00:00,0.0
774,2018-02-28 00:00:00,38.0,-67.0,-0.028477,0.0,-0.003613,0.0,263.292053,0.0000,0.00,...,0.00416,274.752045,54.017105,1.220325,-4.710979,102547.992188,0.0,5588.145508,2018-02-28 03:00:00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2018-02-28 18:00:00,47.0,-83.0,444.931519,18.0,-0.010840,290.0,298.000000,0.1250,0.10,...,0.00377,272.409729,81.699997,1.511052,-1.746793,101324.945312,88.0,5380.987793,2018-02-28 21:00:00,0.0
3,2018-02-28 18:00:00,47.0,-83.5,482.211517,14.0,-0.210840,230.0,308.000000,0.0625,0.18,...,0.00388,272.709747,91.099998,1.641052,-1.606793,101347.945312,100.0,5385.147949,2018-02-28 21:00:00,0.0
2,2018-02-28 18:00:00,47.0,-84.0,448.291534,12.0,-0.010840,230.0,308.000000,0.0625,0.28,...,0.00397,273.109741,98.599998,1.471052,-1.476793,101374.140625,100.0,5389.728027,2018-02-28 21:00:00,0.0
1,2018-02-28 18:00:00,47.0,-84.5,326.531525,6.0,-0.010840,340.0,292.000000,0.0000,0.22,...,0.00384,272.809753,97.300003,1.271052,-1.466793,101403.945312,85.0,5393.687988,2018-02-28 21:00:00,0.0
0,2018-02-28 18:00:00,47.0,-85.0,183.811523,0.0,-0.010840,530.0,221.000000,0.0000,0.06,...,0.00341,271.509735,89.599998,2.211052,-3.056793,101437.546875,2.0,5397.867676,2018-02-28 21:00:00,0.0

In [33]:
df_sorted = the_df.iloc[::-1]

In [34]:
df_sorted

,time,latitude,longitude,orog,cape,cin,dswrf,dlwrf,tp,sde,...,sh2,d2m,r2,u10,v10,prmsl,tcc,gh,valid_time,atmosphere
0,2018-02-28 18:00:00,47.0,-85.0,183.811523,0.0,-0.010840,530.0,221.000000,0.0000,0.06,...,0.00341,271.509735,89.599998,2.211052,-3.056793,101437.546875,2.0,5397.867676,2018-02-28 21:00:00,0.0
1,2018-02-28 18:00:00,47.0,-84.5,326.531525,6.0,-0.010840,340.0,292.000000,0.0000,0.22,...,0.00384,272.809753,97.300003,1.271052,-1.466793,101403.945312,85.0,5393.687988,2018-02-28 21:00:00,0.0
2,2018-02-28 18:00:00,47.0,-84.0,448.291534,12.0,-0.010840,230.0,308.000000,0.0625,0.28,...,0.00397,273.109741,98.599998,1.471052,-1.476793,101374.140625,100.0,5389.728027,2018-02-28 21:00:00,0.0
3,2018-02-28 18:00:00,47.0,-83.5,482.211517,14.0,-0.210840,230.0,308.000000,0.0625,0.18,...,0.00388,272.709747,91.099998,1.641052,-1.606793,101347.945312,100.0,5385.147949,2018-02-28 21:00:00,0.0
4,2018-02-28 18:00:00,47.0,-83.0,444.931519,18.0,-0.010840,290.0,298.000000,0.1250,0.10,...,0.00377,272.409729,81.699997,1.511052,-1.746793,101324.945312,88.0,5380.987793,2018-02-28 21:00:00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
774,2018-02-28 00:00:00,38.0,-67.0,-0.028477,0.0,-0.003613,0.0,263.292053,0.0000,0.00,...,0.00416,274.752045,54.017105,1.220325,-4.710979,102547.992188,0.0,5588.145508,2018-02-28 03:00:00,0.0
775,2018-02-28 00:00:00,38.0,-66.5,-0.028477,0.0,-0.003613,0.0,265.292053,0.0000,0.00,...,0.00437,275.452057,55.517105,1.270325,-5.750979,102529.992188,0.0,5582.325684,2018-02-28 03:00:00,0.0
776,2018-02-28 00:00:00,38.0,-66.0,-0.028477,0.0,-0.003613,0.0,268.292053,0.0000,0.00,...,0.00453,275.952057,56.217106,1.320325,-6.260979,102507.796875,0.0,5575.945801,2018-02-28 03:00:00,0.0
777,2018-02-28 00:00:00,38.0,-65.5,-0.028477,5.0,-0.003613,0.0,270.292053,0.0000,0.00,...,0.00465,276.352051,56.817108,1.330325,-6.540979,102479.796875,0.0,5569.165527,2018-02-28 03:00:00,0.0
778,2018-02-28 00:00:00,38.0,-65.0,-0.028477,6.0,-0.003613,0.0,270.292053,0.0000,0.00,...,0.00475,276.552063,57.417107,1.330325,-6.900979,102445.390625,0.0,5562.325684,2018-02-28 03:00:00,0.0