In [55]:
%load_ext autoreload
%autoreload 2
import sys

# instead of creating a package using setup.py or building from a docker/singularity file,
# import the sister directory of src code to be called on in notebook.
# This keeps the notebook free from code to only hold visualizations and is easier to test
# It also helps keep the state of variables clean such that cells aren't run out of order with a mysterious state
sys.path.append("..")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [56]:
import pandas as pd
import datetime
from datetime import datetime
import time
import numpy as np
from datetime import timedelta
from datetime import date

In [57]:
df1 = pd.read_parquet(
    "/home/aevans/ai2es/cleaned/NAM/2018/01/20180101_nam.t00z_001.parquet"
)

In [58]:
df1

                                            y             x        orog  cape  \
time       latitude  longitude
2018-01-01 38.031165 -84.920231  1.494584e+06  9.075068e+05  240.150024   1.0
           38.023186 -84.785154  1.494584e+06  9.197137e+05  251.590027   1.0
           38.015101 -84.650097  1.494584e+06  9.319206e+05  268.150024   2.0
           38.006910 -84.515061  1.494584e+06  9.441274e+05  280.950012   2.0
           37.998612 -84.380045  1.494584e+06  9.563343e+05  284.070038   2.0
...                                       ...           ...         ...   ...
           47.030162 -65.660569  2.772665e+06  2.396613e+06   62.390026   0.0
           47.008407 -65.515795  2.772665e+06  2.408817e+06   48.710026   0.0
           46.986543 -65.371089  2.772665e+06  2.421022e+06   39.030025   0.0
           46.964570 -65.226452  2.772665e+06  2.433226e+06   27.430025   0.0
           46.942488 -65.081884  2.772665e+06  2.445430e+06   16.310024   0.0

                                      cin  dswrf       dlwrf   tp      sde  \
time       latitude  longitude
2018-01-01 38.031165 -84.920231 -0.369092    0.0  184.546341  0.0  0.00000
           38.023186 -84.785154 -0.269092    0.0  196.646332  0.0  0.00000
           38.015101 -84.650097 -0.069092    0.0  204.946335  0.0  0.00000
           38.006910 -84.515061  0.030908    0.0  196.646332  0.0  0.00000
           37.998612 -84.380045  0.030908    0.0  198.046341  0.0  0.00000
...                                   ...    ...         ...  ...      ...
           47.030162 -65.660569  0.030908    0.0  239.546341  0.0  0.40440
           47.008407 -65.515795  0.030908    0.0  234.846344  0.0  0.39412
           46.986543 -65.371089  0.030908    0.0  239.046341  0.0  0.37700
           46.964570 -65.226452  0.030908    0.0  234.246338  0.0  0.36936
           46.942488 -65.081884  0.030908    0.0  228.946335  0.0  0.34948

                                        t2m      sh2         d2m         r2  \
time       latitude  longitude
2018-01-01 38.031165 -84.920231  262.975159  0.00118  257.931488  67.166031
           38.023186 -84.785154  263.125153  0.00118  258.131470  66.766029
           38.015101 -84.650097  263.185150  0.00119  258.131470  66.766029
           38.006910 -84.515061  263.045166  0.00120  258.231476  68.066032
           37.998612 -84.380045  262.985168  0.00122  258.431488  69.466034
...                                     ...      ...         ...        ...
           47.030162 -65.660569  258.615143  0.00078  253.131485  63.366032
           47.008407 -65.515795  258.785156  0.00080  253.531479  64.766029
           46.986543 -65.371089  258.815155  0.00082  253.831482  66.066032
           46.964570 -65.226452  259.055145  0.00084  254.131485  66.566032
           46.942488 -65.081884  259.345154  0.00086  254.431488  66.666031

                                      u10       v10          prmsl   tcc  \
time       latitude  longitude
2018-01-01 38.031165 -84.920231  1.146992 -3.605448  103540.929688  12.0
           38.023186 -84.785154  0.996992 -3.635448  103524.289062  13.0
           38.015101 -84.650097  0.796992 -3.695448  103509.570312  13.0
           38.006910 -84.515061  0.636992 -3.895448  103500.453125  20.0
           37.998612 -84.380045  0.546992 -4.185448  103491.968750  30.0
...                                   ...       ...            ...   ...
           47.030162 -65.660569  5.456992 -0.885448  101011.968750   0.0
           47.008407 -65.515795  5.506992 -0.515448  100991.007812   0.0
           46.986543 -65.371089  5.706992 -0.145448  100966.687500   0.0
           46.964570 -65.226452  6.176992  0.104552  100939.007812   6.0
           46.942488 -65.081884  6.916992  0.284552  100907.648438  14.0

                                          gh          valid_time
time       latitude  longitude
2018-01-01 38.031165 -84.920231  5430.758301 2018-01-01 01:00:00
           38.023186 -84.785154  5430.230469 2018-01-01 01:00:00
           38.015101 -84.650097  5429.654297 2018-01-01 01:00:00
           38.006910 -84.515061  5429.158691 2018-01-01 01:00:00
           37.998612 -84.380045  5428.710449 2018-01-01 01:00:00
...                                      ...                 ...
           47.030162 -65.660569  5094.646484 2018-01-01 01:00:00
           47.008407 -65.515795  5094.038574 2018-01-01 01:00:00
           46.986543 -65.371089  5093.478516 2018-01-01 01:00:00
           46.964570 -65.226452  5092.950684 2018-01-01 01:00:00
           46.942488 -65.081884  5092.406738 2018-01-01 01:00:00

[13462 rows x 19 columns]

In [59]:
df2 = pd.read_parquet(
    "/home/aevans/ai2es/cleaned/NAM/2022/03/20220301_nam.t00z_003.parquet"
)

In [60]:
df2

                                            y             x        orog  cape  \
time       latitude  longitude
2022-03-01 38.031165 -84.920231  1.494584e+06  9.075068e+05  240.150024   0.0
           38.023186 -84.785154  1.494584e+06  9.197137e+05  251.590027   0.0
           38.015101 -84.650097  1.494584e+06  9.319206e+05  268.150024   0.0
           38.006910 -84.515061  1.494584e+06  9.441274e+05  280.950012   0.0
           37.998612 -84.380045  1.494584e+06  9.563343e+05  284.070038   0.0
...                                       ...           ...         ...   ...
           47.030162 -65.660569  2.772665e+06  2.396613e+06   62.390026   0.0
           47.008407 -65.515795  2.772665e+06  2.408817e+06   48.710026   0.0
           46.986543 -65.371089  2.772665e+06  2.421022e+06   39.030025   0.0
           46.964570 -65.226452  2.772665e+06  2.433226e+06   27.430025   0.0
           46.942488 -65.081884  2.772665e+06  2.445430e+06   16.310024   0.0

                                      cin  dswrf       dlwrf   tp      sde  \
time       latitude  longitude
2022-03-01 38.031165 -84.920231  0.037158    0.0  241.842041  0.0  0.00000
           38.023186 -84.785154  0.037158    0.0  241.942047  0.0  0.00000
           38.015101 -84.650097  0.037158    0.0  242.042038  0.0  0.00000
           38.006910 -84.515061  0.037158    0.0  242.242035  0.0  0.00000
           37.998612 -84.380045  0.037158    0.0  242.742035  0.0  0.00000
...                                   ...    ...         ...  ...      ...
           47.030162 -65.660569  0.037158    0.0  161.942047  0.0  0.15416
           47.008407 -65.515795  0.037158    0.0  162.742035  0.0  0.12488
           46.986543 -65.371089  0.037158    0.0  163.342041  0.0  0.12016
           46.964570 -65.226452  0.037158    0.0  164.042038  0.0  0.11800
           46.942488 -65.081884  0.037158    0.0  164.742035  0.0  0.11336

                                        t2m      sh2         d2m         r2  \
time       latitude  longitude
2022-03-01 38.031165 -84.920231  277.486816  0.00308  270.176117  59.025455
           38.023186 -84.785154  277.406830  0.00310  270.276123  59.725456
           38.015101 -84.650097  277.476807  0.00313  270.376129  59.925453
           38.006910 -84.515061  276.956818  0.00314  270.376129  62.225456
           37.998612 -84.380045  276.446808  0.00313  270.376129  64.325455
...                                     ...      ...         ...        ...
           47.030162 -65.660569  258.676819  0.00064  250.876129  52.125454
           47.008407 -65.515795  259.066803  0.00064  250.976120  50.525455
           46.986543 -65.371089  259.336823  0.00064  251.076126  50.025455
           46.964570 -65.226452  259.656830  0.00065  251.276123  49.325455
           46.942488 -65.081884  259.936829  0.00066  251.376129  48.925453

                                      u10       v10          prmsl  tcc  \
time       latitude  longitude
2022-03-01 38.031165 -84.920231  0.834288  2.071951  102209.859375  1.0
           38.023186 -84.785154  0.964288  2.091951  102216.062500  1.0
           38.015101 -84.650097  1.124288  2.071951  102218.664062  2.0
           38.006910 -84.515061  1.284288  2.011951  102221.062500  3.0
           37.998612 -84.380045  1.364288  1.931951  102223.062500  6.0
...                                   ...       ...            ...  ...
           47.030162 -65.660569  4.544288 -0.868049  102143.062500  0.0
           47.008407 -65.515795  4.824288 -0.798049  102132.265625  0.0
           46.986543 -65.371089  5.074288 -0.738049  102118.062500  0.0
           46.964570 -65.226452  5.444288 -0.748049  102102.460938  0.0
           46.942488 -65.081884  5.904288 -0.848049  102085.664062  0.0

                                          gh          valid_time
time       latitude  longitude
2022-03-01 38.031165 -84.920231  5640.652344 2022-03-01 03:00:00
           38.023186 -84.785154  5640.252441 2022-03-01 03:00:00
           38.015101 -84.650097  5639.900391 2022-03-01 03:00:00
           38.006910 -84.515061  5639.628418 2022-03-01 03:00:00
           37.998612 -84.380045  5639.404297 2022-03-01 03:00:00
...                                      ...                 ...
           47.030162 -65.660569  5209.932617 2022-03-01 03:00:00
           47.008407 -65.515795  5208.844727 2022-03-01 03:00:00
           46.986543 -65.371089  5207.772461 2022-03-01 03:00:00
           46.964570 -65.226452  5206.732422 2022-03-01 03:00:00
           46.942488 -65.081884  5205.724609 2022-03-01 03:00:00

[13462 rows x 19 columns]

In [61]:
the_df = pd.DataFrame()

In [62]:
# consider the start date as 2021-february 1 st
start_date = datetime(2022, 1, 1, 0, 0, 0)

# consider the end date as 2021-march 1 st
end_date = datetime(2022, 1, 2, 23, 59, 59)

# delta time
delta = timedelta(days=1)

In [63]:
savedir = "/home/aevans/ai2es/cleaned/NAM/"
fh = str(3).zfill(3)

In [64]:
# Time interval between data points
delta = timedelta(days=1)

# Loop through the date range
while start_date <= end_date:
    the_df = pd.DataFrame()
    my_date = start_date
    my_time = my_date + timedelta(hours=int(fh))
    # Loop through 24 hours of the day
    for i in np.arange(0, 24, 6):
        my_time = str(my_time)
        print(my_time)
        init = str(i).zfill(2)
        month = str(my_date.strftime("%m"))
        year = str(my_date.strftime("%Y"))
        day = str(my_date.strftime("%d"))

        # Check if the file exists for the given date and forecast hour
        if not os.path.exists(
            f"{savedir}{year}/{month}/{year}{month}{day}_nam.t{init}z_{fh}.parquet"
        ):
            continue
        else:
            # Read the data from the parquet file
            df = pd.read_parquet(
                f"{savedir}{year}/{month}/{year}{month}{day}_nam.t{init}z_{fh}.parquet"
            ).reset_index()
            # Filter data for the specific time
            new_df = df[df["valid_time"] == my_time]
            the_df = pd.concat([new_df, the_df])

            # Increment time by 1 hour
            time_obj = datetime.strptime(my_time, "%Y-%m-%d %H:%M:%S")
            my_time = time_obj + timedelta(hours=6)

    start_date += delta

    # Reverse the order of rows and save the data to a new parquet file
    the_df = the_df.iloc[::-1]

2022-01-01 03:00:00
2022-01-01 09:00:00
2022-01-01 15:00:00
2022-01-01 21:00:00
2022-01-02 03:00:00
2022-01-02 09:00:00
2022-01-02 15:00:00
2022-01-02 21:00:00

In [65]:
the_df["valid_time"].unique()

array(['2022-01-02T03:00:00.000000000', '2022-01-02T09:00:00.000000000',
       '2022-01-02T15:00:00.000000000', '2022-01-02T21:00:00.000000000'],
      dtype='datetime64[ns]')

In [68]:
the_df

,time,latitude,longitude,y,x,orog,cape,cin,dswrf,dlwrf,...,t2m,sh2,d2m,r2,u10,v10,prmsl,tcc,gh,valid_time
13461,2022-01-02 00:00:00,46.942488,-65.081884,2.772665e+06,2.445430e+06,16.310024,0.0,-0.015723,0.0,327.880310,...,275.963623,0.004534,275.644165,98.004128,-0.411598,2.121570,100624.609375,100.0,5453.502930,2022-01-02 03:00:00
13460,2022-01-02 00:00:00,46.964570,-65.226452,2.772665e+06,2.433226e+06,27.430025,0.0,-0.015723,0.0,327.080292,...,275.913605,0.004524,275.594147,98.004128,-0.281598,1.651570,100616.007812,100.0,5451.642578,2022-01-02 03:00:00
13459,2022-01-02 00:00:00,46.986543,-65.371089,2.772665e+06,2.421022e+06,39.030025,0.0,-0.015723,0.0,326.280304,...,275.863617,0.004514,275.534149,98.004128,-0.261598,1.511570,100609.007812,100.0,5449.722656,2022-01-02 03:00:00
13458,2022-01-02 00:00:00,47.008407,-65.515795,2.772665e+06,2.408817e+06,48.710026,0.0,-0.015723,0.0,325.980286,...,275.673615,0.004464,275.364166,98.004128,-0.281598,1.471570,100602.203125,100.0,5448.142578,2022-01-02 03:00:00
13457,2022-01-02 00:00:00,47.030162,-65.660569,2.772665e+06,2.396613e+06,62.390026,0.0,-0.015723,0.0,323.980286,...,275.333618,0.004364,275.004150,98.004128,-0.241598,1.371570,100596.609375,100.0,5446.662598,2022-01-02 03:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2022-01-02 18:00:00,37.998612,-84.380045,1.494584e+06,9.563343e+05,284.070038,19.0,-0.014062,22.0,317.360291,...,275.532349,0.004091,273.878967,89.257835,1.027012,-5.410593,101629.140625,100.0,5560.111816,2022-01-02 21:00:00
3,2022-01-02 18:00:00,38.006910,-84.515061,1.494584e+06,9.441274e+05,280.950012,19.0,-0.014062,22.0,317.260284,...,275.432343,0.004061,273.778992,89.157829,1.067012,-5.350593,101638.937500,100.0,5558.451660,2022-01-02 21:00:00
2,2022-01-02 18:00:00,38.015101,-84.650097,1.494584e+06,9.319206e+05,268.150024,20.0,-0.014062,22.0,317.560272,...,275.432343,0.004041,273.778992,88.657829,1.107012,-5.290593,101648.140625,100.0,5556.751953,2022-01-02 21:00:00
1,2022-01-02 18:00:00,38.023186,-84.785154,1.494584e+06,9.197137e+05,251.590027,21.0,-0.014062,26.0,317.660278,...,275.532349,0.004041,273.778992,88.257835,1.087012,-5.250593,101652.937500,100.0,5555.031738,2022-01-02 21:00:00
0,2022-01-02 18:00:00,38.031165,-84.920231,1.494584e+06,9.075068e+05,240.150024,19.0,-0.014062,27.0,317.460266,...,275.632355,0.004031,273.778992,87.757835,1.057012,-5.150593,101657.734375,100.0,5553.412109,2022-01-02 21:00:00

In [66]:
df_sorted = the_df.iloc[::-1]

In [67]:
df_sorted

,time,latitude,longitude,y,x,orog,cape,cin,dswrf,dlwrf,...,t2m,sh2,d2m,r2,u10,v10,prmsl,tcc,gh,valid_time
0,2022-01-02 18:00:00,38.031165,-84.920231,1.494584e+06,9.075068e+05,240.150024,19.0,-0.014062,27.0,317.460266,...,275.632355,0.004031,273.778992,87.757835,1.057012,-5.150593,101657.734375,100.0,5553.412109,2022-01-02 21:00:00
1,2022-01-02 18:00:00,38.023186,-84.785154,1.494584e+06,9.197137e+05,251.590027,21.0,-0.014062,26.0,317.660278,...,275.532349,0.004041,273.778992,88.257835,1.087012,-5.250593,101652.937500,100.0,5555.031738,2022-01-02 21:00:00
2,2022-01-02 18:00:00,38.015101,-84.650097,1.494584e+06,9.319206e+05,268.150024,20.0,-0.014062,22.0,317.560272,...,275.432343,0.004041,273.778992,88.657829,1.107012,-5.290593,101648.140625,100.0,5556.751953,2022-01-02 21:00:00
3,2022-01-02 18:00:00,38.006910,-84.515061,1.494584e+06,9.441274e+05,280.950012,19.0,-0.014062,22.0,317.260284,...,275.432343,0.004061,273.778992,89.157829,1.067012,-5.350593,101638.937500,100.0,5558.451660,2022-01-02 21:00:00
4,2022-01-02 18:00:00,37.998612,-84.380045,1.494584e+06,9.563343e+05,284.070038,19.0,-0.014062,22.0,317.360291,...,275.532349,0.004091,273.878967,89.257835,1.027012,-5.410593,101629.140625,100.0,5560.111816,2022-01-02 21:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13457,2022-01-02 00:00:00,47.030162,-65.660569,2.772665e+06,2.396613e+06,62.390026,0.0,-0.015723,0.0,323.980286,...,275.333618,0.004364,275.004150,98.004128,-0.241598,1.371570,100596.609375,100.0,5446.662598,2022-01-02 03:00:00
13458,2022-01-02 00:00:00,47.008407,-65.515795,2.772665e+06,2.408817e+06,48.710026,0.0,-0.015723,0.0,325.980286,...,275.673615,0.004464,275.364166,98.004128,-0.281598,1.471570,100602.203125,100.0,5448.142578,2022-01-02 03:00:00
13459,2022-01-02 00:00:00,46.986543,-65.371089,2.772665e+06,2.421022e+06,39.030025,0.0,-0.015723,0.0,326.280304,...,275.863617,0.004514,275.534149,98.004128,-0.261598,1.511570,100609.007812,100.0,5449.722656,2022-01-02 03:00:00
13460,2022-01-02 00:00:00,46.964570,-65.226452,2.772665e+06,2.433226e+06,27.430025,0.0,-0.015723,0.0,327.080292,...,275.913605,0.004524,275.594147,98.004128,-0.281598,1.651570,100616.007812,100.0,5451.642578,2022-01-02 03:00:00
13461,2022-01-02 00:00:00,46.942488,-65.081884,2.772665e+06,2.445430e+06,16.310024,0.0,-0.015723,0.0,327.880310,...,275.963623,0.004534,275.644165,98.004128,-0.411598,2.121570,100624.609375,100.0,5453.502930,2022-01-02 03:00:00